// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE

  LOGOUT

  STARTUP

  TEMPERATURE_REQUEST
  TEMPERATURE_RECEIVE
  TEMPERATURE_FAILURE

  LOOKUP_REQUEST
  LOOKUP_RECEIVE
  LOOKUP_FAILURE

  QUOTE_REQUEST
  QUOTE_RECEIVE
  QUOTE_FAILURE
`)
